### ISSUE TITLE
Move instances of mmap advise to be gated by cfg target_os

### ISSUE THREAD

**Issue by vswarte** [soulsmods/fstools-rs#35]
We've moved away from `gmp-mpfr-sys` in #34 to make the RSA impl more easy to compile on Windows, however compiling for windows is still gated by #25 as well as some errors involving `memmap2` (described in this issue).

Currently, when compiling or windows, we still try and consume memmap2's Advice API. Advising is an optimization and not required for the code to function. This means that we can simple opt to not advise on windows systems.

The idea (for now anyways) is to apply `#[cfg(target_os = "linux")]` to https://github.com/soulsmods/fstools-rs/blob/07b07b4c95485ab3954ad14a2a7bd85426a4932f/crates/dvdbnd/src/lib.rs#L143 as well as the `Advice` import (since this isn't exposed in any capacity on windows builds causing an error at import).

**Comment by garyttierney** [comment]
> The idea (for now anyways) is to apply #[cfg(target_os = "linux")] to

Other unix systems support `madvise`, so this should be `#[cfg(unix)]`
